import { GoogleGenAI } from "@google/genai";
import { DogConfig, DogStyle } from "../types";
import { STYLE_PROMPTS } from "../constants";

export const generateDogImage = async (config: DogConfig): Promise<string> => {
  const apiKey = import.meta.env.VITE_API_KEY;
  if (!apiKey) {
    throw new Error("API Key is missing.");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  // Construct the prompt based on the specific logic required
  const breedsString = config.breeds.join(" and ");
  const promptBuilder = STYLE_PROMPTS[config.style];
  
  if (!promptBuilder) {
    throw new Error("Invalid style selected");
  }

  const prompt = promptBuilder(breedsString, config.pose);

  // Use the image generation model
  // Note: Using gemini-2.5-flash-image for speed and general availability
  const response = await ai.models.generateContent({
    model: 'imagen-3.0-generate-001',
    contents: {
      parts: [
        {
          text: prompt,
        },
      ],
    },
    config: {
      imageConfig: {
        aspectRatio: "1:1",
        // imageSize is only for Pro model, Flash ignores it or might error if set incorrectly, so we omit for Flash
      },
    },
  });

  // Extract image from response
  let base64Image = "";
  
  if (response.candidates && response.candidates[0].content && response.candidates[0].content.parts) {
     for (const part of response.candidates[0].content.parts) {
       if (part.inlineData) {
         base64Image = part.inlineData.data;
         break;
       }
     }
  }

  if (!base64Image) {
    throw new Error("No image generated by the model. Please try again.");
  }

  return `data:image/png;base64,${base64Image}`;
};
